const networkIDs = {
	MAINNET_CODE: 1,
	CLASSIC_CODE: 61,
	ROPSTEN_CODE: 3,
	RINKEBY_CODE: 4,
	GOERLI_CODE: 5,
	KOVAN_CODE: 42,
	SOKOL_CODE: 77,
	POA_CORE_CODE: 99,
	XDAI_CODE: 100,
	XDC_CODE: 50,
	XDC_TESTNET_CODE: 51,
}

module.exports = {
	networkIDs
}